"""Export the UI art that C# needs:

* src/UI/Pix/PixData.g.cs  — palette, corner profiles and every ASCII sprite grid (icons, hearts, knob...)
* assets/textures/ui.png + atlas rects in PixData.g.cs — fixed-size decorative pieces that are baked here once
  (panel body, stage, ribbon), since they use Python-only details such as the stage's seeded twinkles.

Everything stateful (buttons, pills, keys, candies...) is drawn at runtime by the C# port of ui.py,
so the game and the mockups stay pixel-identical.
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image

import ui
from ui import P

ROOT = Path(__file__).resolve().parent.parent
OUT_CS = ROOT / 'src' / 'UI' / 'Pix' / 'PixData.g.cs'
OUT_PNG = ROOT / 'assets' / 'textures' / 'ui.png'

PANEL_W, PANEL_H = 232, 160


def cs_color(c) -> str:
    r, g, b, a = c
    return f'new Color({r}, {g}, {b}, {a})'


def cs_grid(rows) -> str:
    return 'new[] { ' + ', '.join('"' + r + '"' for r in rows) + ' }'


def pascal(name: str) -> str:
    return ''.join(p[:1].upper() + p[1:] for p in name.split('_'))


def bake_atlas():
    pieces = {
        'Panel': ui.panel(PANEL_W, PANEL_H),
        'Stage': ui.stage(60, 54),
        'Ribbon': ui.ribbon(104, 15),
    }
    # simple shelf packing, one row per piece
    w = max(p.width for p in pieces.values())
    h = sum(p.height + 1 for p in pieces.values())
    sheet = Image.new('RGBA', (w, h), (0, 0, 0, 0))
    rects = {}
    y = 0
    for name, im in pieces.items():
        sheet.alpha_composite(im, (0, y))
        rects[name] = (0, y, im.width, im.height)
        y += im.height + 1
    sheet.save(OUT_PNG)
    return rects


def main():
    rects = bake_atlas()
    lines = [
        '// <auto-generated> by art/export_ui.py from art/ui.py — do not edit by hand. </auto-generated>',
        'using System.Collections.Generic;',
        'using Microsoft.Xna.Framework;',
        '',
        'namespace JunimoOrchestra.UI.Pix',
        '{',
        '    internal static partial class PixData',
        '    {',
        '        /// <summary>The "strawberry-milk music box" palette.</summary>',
        '        public static readonly Dictionary<string, Color> P = new()',
        '        {',
    ]
    for k, c in P.items():
        lines.append(f'            ["{k}"] = {cs_color(c)},')
    lines += ['        };', '']
    lines.append('        /// <summary>Rounded-corner insets per row, by radius.</summary>')
    lines.append('        public static readonly int[][] Corners =')
    lines.append('        {')
    for r in range(max(ui.CORNERS) + 1):
        lines.append('            new int[] { ' + ', '.join(str(v) for v in ui.CORNERS[r]) + ' },')
    lines += ['        };', '']
    lines.append('        /// <summary>Icon grids: O = ink colour, W = highlight colour, A = accent.</summary>')
    lines.append('        public static readonly Dictionary<string, string[]> Icons = new()')
    lines.append('        {')
    for k, rows in list(ui.ICONS_SRC.items()) + list(ui.NOTE_VALUES.items()):
        lines.append(f'            ["{k}"] = {cs_grid(rows)},')
    lines += ['        };', '']
    grids = {
        'HeartKnob': ui.HEART_KNOB,
        'Treble': ui.TREBLE,
        'Bass': ui.BASS,
        'Notehead': ui.NOTEHEAD,
        'Sharp': ui.SHARP,
    }
    for name, rows in grids.items():
        lines.append(f'        public static readonly string[] {name} = {cs_grid(rows)};')
    lines.append('')
    lines.append('        /// <summary>Baked pieces in assets/textures/ui.png.</summary>')
    for name, (x, y, w, h) in rects.items():
        lines.append(f'        public static readonly Rectangle Atlas{name} = new({x}, {y}, {w}, {h});')
    lines += ['    }', '}', '']
    OUT_CS.parent.mkdir(parents=True, exist_ok=True)
    OUT_CS.write_text('\n'.join(lines), encoding='utf-8')
    print('wrote', OUT_CS, 'and', OUT_PNG, rects)


if __name__ == '__main__':
    main()
