// <auto-generated> by art/export_ui.py from art/ui.py — do not edit by hand. </auto-generated>
using System.Collections.Generic;
using Microsoft.Xna.Framework;

namespace JunimoOrchestra.UI.Pix
{
    internal static partial class PixData
    {
        /// <summary>The "strawberry-milk music box" palette.</summary>
        public static readonly Dictionary<string, Color> P = new()
        {
            ["berry"] = new Color(110, 43, 75, 255),
            ["berry2"] = new Color(161, 63, 104, 255),
            ["rose"] = new Color(232, 120, 159, 255),
            ["rose2"] = new Color(208, 90, 132, 255),
            ["pink"] = new Color(247, 169, 197, 255),
            ["blush"] = new Color(255, 214, 228, 255),
            ["milk"] = new Color(255, 247, 238, 255),
            ["milk2"] = new Color(248, 232, 217, 255),
            ["milk3"] = new Color(238, 213, 192, 255),
            ["milk4"] = new Color(217, 184, 160, 255),
            ["ging1"] = new Color(255, 241, 245, 255),
            ["ging2"] = new Color(255, 227, 237, 255),
            ["ging3"] = new Color(253, 211, 226, 255),
            ["gold"] = new Color(245, 199, 93, 255),
            ["gold2"] = new Color(212, 149, 47, 255),
            ["gold3"] = new Color(255, 234, 168, 255),
            ["goldD"] = new Color(138, 90, 28, 255),
            ["ink"] = new Color(91, 39, 66, 255),
            ["ink2"] = new Color(160, 100, 127, 255),
            ["ink3"] = new Color(201, 150, 173, 255),
            ["plum"] = new Color(59, 33, 64, 255),
            ["plum2"] = new Color(77, 43, 82, 255),
            ["plum3"] = new Color(99, 58, 103, 255),
            ["cur"] = new Color(216, 67, 107, 255),
            ["cur2"] = new Color(168, 38, 82, 255),
            ["cur3"] = new Color(244, 113, 150, 255),
            ["curD"] = new Color(110, 18, 54, 255),
            ["wood"] = new Color(211, 154, 98, 255),
            ["wood2"] = new Color(170, 109, 63, 255),
            ["wood3"] = new Color(236, 192, 138, 255),
            ["woodD"] = new Color(107, 58, 30, 255),
            ["mint"] = new Color(155, 227, 192, 255),
            ["mint2"] = new Color(98, 191, 150, 255),
            ["mint3"] = new Color(213, 247, 230, 255),
            ["mintD"] = new Color(47, 110, 88, 255),
            ["keyW"] = new Color(255, 253, 248, 255),
            ["keyW2"] = new Color(244, 228, 216, 255),
            ["keyO"] = new Color(140, 93, 114, 255),
            ["keyB"] = new Color(61, 36, 64, 255),
            ["keyB2"] = new Color(95, 60, 98, 255),
            ["keyB3"] = new Color(38, 19, 42, 255),
            ["white"] = new Color(255, 255, 255, 255),
        };

        /// <summary>Rounded-corner insets per row, by radius.</summary>
        public static readonly int[][] Corners =
        {
            new int[] {  },
            new int[] { 1 },
            new int[] { 2, 1 },
            new int[] { 3, 1, 1 },
            new int[] { 4, 2, 1, 1 },
            new int[] { 5, 3, 2, 1, 1 },
            new int[] { 6, 4, 3, 2, 1, 1 },
            new int[] { 7, 5, 3, 2, 2, 1, 1 },
            new int[] { 8, 5, 4, 3, 2, 1, 1, 1 },
        };

        /// <summary>Icon grids: O = ink colour, W = highlight colour, A = accent.</summary>
        public static readonly Dictionary<string, string[]> Icons = new()
        {
            ["note"] = new[] { "..OO.", "..OWO", "..O.O", "..O..", "OOO..", "OOO..", ".O..." },
            ["notes"] = new[] { "...OOOO", "...OWWO", "...O..O", "...O..O", ".OOO.OO", "OOOOOOO", ".O...O." },
            ["speaker"] = new[] { "....O...", "...OO.O.", "OOOWO..O", "OWWWO.OO", "OWWWO..O", "OOOWO.O.", "...OO...", "....O..." },
            ["play"] = new[] { "O....", "OO...", "OWO..", "OWWO.", "OWO..", "OO...", "O...." },
            ["copy"] = new[] { ".OOOOO..", ".OWWWO..", "OOOOOWO.", "OWWWOOO.", "OWWWWO..", "OWWWWO..", "OWWWWO..", "OOOOOO.." },
            ["paste"] = new[] { "..OOO...", "OOWWWOO.", "OWOOOWO.", "OWWWWWO.", "OWOOOWO.", "OWWWWWO.", "OWOOWWO.", "OOOOOOO." },
            ["check"] = new[] { "......O", ".....OO", "O...OO.", "OO.OO..", ".OOO...", "..O...." },
            ["reset"] = new[] { "O.OOO..", "OO...O.", "OOO...O", "......O", "O.....O", ".O...O.", "..OOO.." },
            ["x"] = new[] { "OO...OO", ".OO.OO.", "..OOO..", ".OO.OO.", "OO...OO" },
            ["left"] = new[] { "...O", "..OO", ".OOO", "OOOO", ".OOO", "..OO", "...O" },
            ["right"] = new[] { "O...", "OO..", "OOO.", "OOOO", "OOO.", "OO..", "O..." },
            ["up"] = new[] { "...O...", "..OOO..", ".OOOOO.", "OOOOOOO" },
            ["down"] = new[] { "OOOOOOO", ".OOOOO.", "..OOO..", "...O..." },
            ["heart"] = new[] { ".OO.OO.", "OWOOOOO", "OOOOOOO", ".OOOOO.", "..OOO..", "...O..." },
            ["sparkle"] = new[] { "..O..", "..O..", "OOWOO", "..O..", "..O.." },
            ["star"] = new[] { "...O...", "..OWO..", "OOOWOOO", ".OWWWO.", "..OOO..", ".OO.OO.", ".O...O." },
            ["keys"] = new[] { "OOOOOOOOO", "OW.W.WW.O", "OW.W.WW.O", "OWWWWWWWO", "OWOWOWOWO", "OOOOOOOOO" },
            ["dice"] = new[] { ".OOOOOO.", "OWWWWWWO", "OWOWWWWO", "OWWWOWWO", "OWWWWWWO", "OWWWWWOO", "OWWWWWWO", ".OOOOOO." },
            ["stop"] = new[] { "OOOOO", "OOOOO", "OOOOO", "OOOOO", "OOOOO" },
            ["arrow_up"] = new[] { "..O..", ".OOO.", "O.O.O", "..O..", "..O..", "..O.." },
            ["arrow_down"] = new[] { "..O..", "..O..", "..O..", "O.O.O", ".OOO.", "..O.." },
            ["arrow_left"] = new[] { "..O...", ".O....", "OOOOOO", ".O....", "..O..." },
            ["arrow_right"] = new[] { "...O..", "....O.", "OOOOOO", "....O.", "...O.." },
            ["plus"] = new[] { "..O..", "..O..", "OOOOO", "..O..", "..O.." },
            ["minus"] = new[] { "OOOOO" },
            ["dot"] = new[] { "OO", "OO" },
            ["space"] = new[] { "O.....O", "OOOOOOO" },
            ["wave"] = new[] { "..OO.....", ".O..O....", "O....O..O", "......OO." },
            ["link"] = new[] { "OOO......", "OWO......", "OOOOOO...", "....O....", "...OOOOO.", "....O.OWO", "......OOO" },
            ["globe"] = new[] { "..OOOOO..", ".OWOWOWO.", "OWWOWOWWO", "OOOOOOOOO", "OWWOWOWWO", ".OWOWOWO.", "..OOOOO.." },
            ["mouse_l"] = new[] { ".OOOOO.", "OAAOWWO", "OAAOWWO", "OOOOOOO", "OWWWWWO", "OWWWWWO", ".OWWWO.", "..OOO.." },
            ["mouse_r"] = new[] { ".OOOOO.", "OWWOAAO", "OWWOAAO", "OOOOOOO", "OWWWWWO", "OWWWWWO", ".OWWWO.", "..OOO.." },
            ["person"] = new[] { "..OO..", "..OO..", ".OOOO.", "O.OO.O", "..OO..", ".O..O.", ".O..O." },
            ["chicken"] = new[] { "..OO....", ".OWOO...", "OOWWO...", "..OWWOOO", "..OWWWWO", "...OWWO.", "....OO..", "....O.O." },
            ["trash"] = new[] { ".OOOOO.", "OOOOOOO", ".OWOWO.", ".OWOWO.", ".OWOWO.", ".OOOOO." },
            ["rest4"] = new[] { "..O..", "...O.", "..OO.", ".OO..", "..O..", "...O.", "..OO.", ".O...", "O...." },
            ["sn1"] = new[] { ".OOO.", "O...O", "O...O", ".OOO." },
            ["sn2"] = new[] { "...O", "...O", "...O", "...O", ".OOO", "O..O", ".OO." },
            ["sn4"] = new[] { "...O", "...O", "...O", "...O", ".OOO", "OOOO", ".OO." },
            ["sn8"] = new[] { "...O.", "...OO", "...O.", "...O.", ".OOO.", "OOOO.", ".OO.." },
            ["sn16"] = new[] { "...O.", "...OO", "...OO", "...O.", ".OOO.", "OOOO.", ".OO.." },
            ["three"] = new[] { "OOO", "..O", ".OO", "..O", "OOO" },
            ["dotdot"] = new[] { "OO", "OO" },
            ["walk"] = new[] { "..OO..", "..OO..", ".OOOO.", "O.OO.O", "..OO..", ".O..O.", "O....O" },
            ["n16"] = new[] { "....O..", "....OO.", "....O.O", "....OO.", "....O.O", "....O..", ".OOOO..", "OOOOO..", ".OOO..." },
            ["n8"] = new[] { "....O..", "....OO.", "....O.O", "....O..", "....O..", "....O..", ".OOOO..", "OOOOO..", ".OOO..." },
            ["n4"] = new[] { "....O", "....O", "....O", "....O", "....O", "....O", ".OOOO", "OOOOO", ".OOO." },
            ["n2"] = new[] { "....O", "....O", "....O", "....O", "....O", "....O", ".OOOO", "O...O", ".OOO." },
            ["n1"] = new[] { ".....", ".....", ".....", ".....", ".....", ".OOO.", "O...O", "O...O", ".OOO." },
            ["hold"] = new[] { ".......", ".......", "..OOO..", ".O...O.", "O.....O", ".......", "...O...", "..OOO..", "...O..." },
        };

        public static readonly string[] HeartKnob = new[] { "..OOO...OOO..", ".ORRRO.ORRRO.", "ORWWRRORRRRRO", "ORWRRRRRRRRRO", "ORRRRRRRRRRdO", ".ORRRRRRRRdO.", "..ORRRRRRdO..", "...ORRRRdO...", "....ORRdO....", ".....OdO.....", "......O......" };
        public static readonly string[] Treble = new[] { "....OO.", "...O..O", "...O..O", "...O.O.", "...OO..", "..OO...", ".OO....", "OO..O..", "O..OOO.", "O.O.O.O", "O.O.O.O", ".O..O.O", "..OOOO.", "....O..", "....O..", "..OOO..", "..OO..." };
        public static readonly string[] Bass = new[] { ".OOO...", "O...O.O", "OO..O..", "OO..O.O", "...O...", "..O....", ".O.....", "O......" };
        public static readonly string[] Notehead = new[] { ".OOO.", "OOOOO", "OOOOO", ".OOO." };
        public static readonly string[] Sharp = new[] { ".O.O.", "OOOOO", ".O.O.", "OOOOO", ".O.O." };

        /// <summary>Baked pieces in assets/textures/ui.png.</summary>
        public static readonly Rectangle AtlasPanel = new(0, 0, 232, 160);
        public static readonly Rectangle AtlasStage = new(0, 161, 60, 54);
        public static readonly Rectangle AtlasRibbon = new(0, 216, 104, 19);
    }
}
